### ISSUE TITLE
"Missing sql for layer 0 options"

### ISSUE THREAD

**Issue by danicarrion** [CartoDB/cartodb#7368]
How to reproduce:

1) Create a dataset

2) Create a map with the current editor

3) You can verify that embed_map and createVis work (regular, not DI)

4) Now open the new editor for that add a widget (I tried myself with a formula one, if it matters)

5) Verify that embed_map and createVis (again, not DI) now don't work, and the request to the maps API shows the error in the title.

6) Verify that createDashboard doesn't work either, showing the same error (checked against the frozen version of DI, will test against the latest in a minute)

cc @xavijam @juanignaciosl

**Comment by juanignaciosl** [comment]
cc @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
@danicarrion can you please define "embed_map and createVis"?

**Comment by alonsogarciapablo** [comment]
Also, where are you seeing this error?

**Comment by danicarrion** [comment]
"embed map", I mean the public URL for the map, something like: https://team.cartodb.com/u/dcarrion/viz/980d31d8-1783-11e6-88e3-0e674067d321/embed_map

and for createVis I mean doing a createVis on cartodb.js using the viz.json provided by the editor

I see that error when sending the request for the layergroup to the maps api: https://dcarrion.cartodb.com/api/v1/map?stat_tag=980d31d8-1783-11e6-88e3-0e674067d321&config=%7B%22version%22%3A%221.0.1%22%2C%22stat_tag%22%3A%22980d31d8-1783-11e6-88e3-0e674067d321%22%2C%22layers%22%3A%5B%7B%22type%22%3A%22cartodb%22%2C%22options%22%3A%7B%22cartocss%22%3A%22%2F**%20simple%20visualization%20*%2F%5Cn%5Cn%23null%7B%5Cn%20%20marker-fill-opacity%3A%200.9%3B%5Cn%20%20marker-line-color%3A%20%23FFF%3B%5Cn%20%20marker-line-width%3A%201%3B%5Cn%20%20marker-line-opacity%3A%201%3B%5Cn%20%20marker-placement%3A%20point%3B%5Cn%20%20marker-type%3A%20ellipse%3B%5Cn%20%20marker-width%3A%2010%3B%5Cn%20%20marker-fill%3A%20%23FF6600%3B%5Cn%20%20marker-allow-overlap%3A%20true%3B%5Cn%7D%22%2C%22cartocss_version%22%3A%222.1.1%22%2C%22interactivity%22%3A%5B%22cartodb_id%22%5D%7D%7D%5D%7D&callback=_cdbc_3170137435_1

**Comment by alonsogarciapablo** [comment]
@danicarrion what version of CartoDB.js?

**Comment by rochoa** [comment]
The layer is missing the sql option:

```
{
    "layers": [
        {
            "options": {
                "cartocss": "/** simple visualization */\n\n#null{\n  marker-fill-opacity: 0.9;\n  marker-line-color: #FFF;\n  marker-line-width: 1;\n  marker-line-opacity: 1;\n  marker-placement: point;\n  marker-type: ellipse;\n  marker-width: 10;\n  marker-fill: #FF6600;\n  marker-allow-overlap: true;\n}",
                "cartocss_version": "2.1.1",
                "interactivity": [
                    "cartodb_id"
                ]
            },
            "type": "cartodb"
        }
    ],
    "stat_tag": "980d31d8-1783-11e6-88e3-0e674067d321",
    "version": "1.0.1"
}
```

**Comment by alonsogarciapablo** [comment]
For some reason [the viz.json that is being used](https://team.cartodb.com/u/dcarrion/api/v2/viz/980d31d8-1783-11e6-88e3-0e674067d321/viz.json) in that "old embed" has the `source` option instead of the `sql` option for the layer... cc: @juanignaciosl

**Comment by juanignaciosl** [comment]
It's probably related to the layer analysis: `"source":{"id":"a0"}`

```

**Comment by juanignaciosl** [comment]
In fact the layer option is stored like `"source":"a0"`, and the vizjson creates the object structure moving the id inside.

cc @xavijam

**Comment by rochoa** [comment]
But in viz.json v2 we should not use source, right?

**Comment by danicarrion** [comment]
v3 is not working either, not even with current deep-insights.js, I've just confirmed

**Comment by juanignaciosl** [comment]
It's a backwards compatibility issue. There's no sql in that layer options. Should vizjson try to check whether the source is an analysis id and take the sql from that analysis for vizjson v2?

**Comment by juanignaciosl** [comment]
@danicarrion I don't know why new is not working, but since it's a layer with an analysis it's not meant to have `sql` but `source`, isn't it, @alonsogarciapablo ?

**Comment by alonsogarciapablo** [comment]
The [new embed for this map](https://team.cartodb.com/u/dcarrion/editor/980d31d8-1783-11e6-88e3-0e674067d321/embed) is actually working :)

> since it's a layer with an analysis it's not meant to have sql but source

Yes, in the context of the new editor that is true.

**Comment by rochoa** [comment]
I changed the title as I already released a fix for regression described at https://github.com/CartoDB/Windshaft-cartodb/issues/446.

**Comment by danicarrion** [comment]
my js dashboard is working now!!! thanks!

**Comment by danicarrion** [comment]
Actually, the map is displayed, but the dashboard object after createDashboard is undefined (err is null). I'm investigating now if this is related to this issue.

**Comment by danicarrion** [comment]
false alarm, it seems to work alright O:-)

the "old" embed_map is still not working though

**Comment by alonsogarciapablo** [comment]
Can we close this then?

**Comment by danicarrion** [comment]
no, the old embed_map and related still fail

**Comment by alonsogarciapablo** [comment]
Old embeds won't work anymore after you "edit" a map using the new editor...

**Comment by javisantana** [comment]
we should send the sql from the first node in order to break maps.

It's not the best solution but good enough

**Comment by javitonino** [comment]
Fixed for normal layers. There are still some problems with Torque layers that are being tracked at #7413 and #7422
